In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

test = pd.read_csv('test.csv')

test.pc_Sent.tail()

,run,type,module,name,attrname,attrvalue,value,vectime,vecvalue
76,General-0-20191031-12:24:28-10992,vector,CompleteNetwork7.node_10,pc_Sent,NaN,NaN,NaN,64.3 64.3 64.3 67.1 67.1 67.1,1 2 3 4 5 6
77,General-0-20191031-12:24:28-10992,vector,CompleteNetwork7.node_3,pc_Sent,NaN,NaN,NaN,64.5 64.5 66.6 66.9 67.3 67.3,1 2 3 4 5 6
78,General-0-20191031-12:24:28-10992,vector,CompleteNetwork7.node_1,pc_Sent,NaN,NaN,NaN,64.7 64.7 66.4 66.7 67.5 67.8,1 2 3 4 5 6
79,General-0-20191031-12:24:28-10992,vector,CompleteNetwork7.node_0,pc_Sent,NaN,NaN,NaN,64.9 66.5 68.3,1 2 3
80,General-0-20191031-12:24:28-10992,vector,CompleteNetwork7.node_8,pc_Sent,NaN,NaN,NaN,65.7 65.7 65.7 69 69 69,1 2 3 4 5 6